** Fixes some annoying stuff
1. make cursor style to bar

2. disable backup file
#+BEGIN_SRC emacs-lisp
  (setq make-backup-files nil)
#+END_SRC
use C-' to open another buffer to edit source code.
Make source code fancy in the org file.
#+BEGIN_SRC emacs-lisp
  (require 'org)
  (setq org-src-fontify-natively t)
#+END_SRC

3. enable recentf-mode
#+BEGIN_SRC emacs-lisp
  (require 'recentf)
  (recentf-mode 1)
  (setq recentf-max-menu-items 25)
  (global-set-key "\C-x\ \C-r" 'recentf-open-files)
#+END_SRC

5. add delete selection mode
#+BEGIN_SRC emacs-lisp
  (delete-selection-mode t)
#+END_SRC


** Make Emacs more fancy
1. Open with full screen
#+BEGIN_SRC emacs-lisp
  (setq initial-frame-alist (quote ((fullscreen . maximized))))
#+END_SRC

2. show match parents
#+BEGIN_SRC emacs-lisp
  (add-hook 'emacs-lisp-mode-hook 'show-paren-mode)
#+END_SRC
It has a flaw, we will use more powerful package in the future.
When the cursor stop at the middle of parents, it can't highlight the parents.

3. Highlight current line (global-hl-line-mode)
#+BEGIN_SRC emacs-lisp
  (global-hl-line-mode t)
#+END_SRC

** Improve built-in package system
1. make package system more powerful with Melpa
#+BEGIN_SRC emacs-lisp
  (when (>= emacs-major-version 24)
    (require 'package)
    (package-initialize)
    (add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
    )
  (require 'cl)

  ;; add whatever packages you want here
  (defvar bluesands/packages '(
                               company
                               ) "Defautl packages")

  (defun bluesands/packages-installed-p ()
    (loop for pkg in bluesands/packages
          when (not (package-installed-p pkg)) do (return nil)
          finally (return t)))

  (unless (bluesands/packages-installed-p)
    (message "%s" "Refreshing package database...")
    (package-refresh-contents)
    (dolist (pkg bluesands/packages)
      (when (not (package-installed-p pkg))
        (package-install pkg))))
#+END_SRC

1. install a theme (monokai)
2. install hungry delete mode
3. package-list-packages (add/delete/update packages)
4. install and configure smex and ivy mode
5. use customize-group to customize the package settings
6. install and configure smartparents mode
7. Don't try to update the package daily, the updaing process might failed.

(tips: press M-RET to fix the order, you could also use M-RET to and new headings, cheers!)

** Org-mode(Bonus Time)

*** Agenda files and agenda view
1. one gtd.org file

#+BEGIN_SRC emacs-lisp
  (setq org-agenda-files '("~/org"))
  (global-set-key (kbd "C-c a") 'org-agenda)
#+END_SRC

*** Learn how to schedule items and set deadline
1. C-c C-s to schedule item
2. C-c C-d to set deadline of item
